---
title: Learner, hopefully for life.
timezone: IST
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
highlighter: rouge
markdown: kramdown
rdiscount:
       extensions: [smart]
permalink: "/:title.html"
paginate: 5
port: 3000
safe: true
local: false
# edit here to achieve your personal greatness
url: http://www.slashsumit.in
baseurl:
author: Sumit Murari
description: Place to keep some thoughts
avatar: profile.png
email: email@slashsumit.in
email_feedback: true
github: murarisumit
# aboutme: murarisumit
linkedin: murarisumit
# stackoverflow: 2735833
stackoverflow_story: murarisumit
google_analytics: UA-64117471-1
gems:
- jekyll-admin
- jekyll-paginate

# needed for travis-ci build
exclude: [vendor]
